baseURL = 'https://george.chemmala.com'
languageCode = 'en-us'
title = 'George Chemmala'
theme = ['typo']

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "George Chemmala's Personal Website"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = '''
Hi there <span class="wave-hand" style="display:inline-block; transition: transform 0.2s;">👋</span>
<style>
.wave-hand {
    display: inline-block;
    transition: transform 0.2s;
}
.wave-hand:hover {
    animation: wave-animation 1s;
    animation-fill-mode: forwards;
}
.wave-hand.waving {
    animation: wave-animation 1s;
    animation-fill-mode: forwards;
}
@keyframes wave-animation {
    0% { transform: rotate(0deg);}
    30% { transform: rotate(-10deg);}
    75% { transform: rotate(10deg);}
    100% { transform: rotate(0deg);}
}
</style>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const hand = document.querySelector('.wave-hand');
    let timeout;
    hand.addEventListener('mouseenter', function() {
        hand.classList.add('waving');
        clearTimeout(timeout);
    });
    hand.addEventListener('mouseleave', function() {
        timeout = setTimeout(() => {
            hand.classList.remove('waving');
        }, 1000);
    });
    hand.addEventListener('animationend', function() {
        hand.classList.remove('waving');
    });
});
</script>
'''
homeIntroContent = '''
I'm a junior at Brown University studying Computer Science and Mathematics, with current interests in cryptography, deep learning, and formal proof verification.

Check out my projects below, but also take a look at some of my [other](/other) stuff
<br>
<a href="#" id="feeling-lucky-link" style="color: var(--bg);">I'm feeling lucky</a>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const luckyLink = document.getElementById('feeling-lucky-link');
    if (luckyLink) {
        luckyLink.addEventListener('click', async function(event) {
            event.preventDefault();
            try {
                const res = await fetch('/sitemap.xml');
                const text = await res.text();
                const parser = new DOMParser();
                const xml = parser.parseFromString(text, 'application/xml');
                const urls = Array.from(xml.querySelectorAll('url > loc'))
                    .map(loc => new URL(loc.textContent).pathname)
                    .filter(path => path !== '/google21d0060bd8dc65b8/')
                    .filter(path => path !== '/yo/')
                    .filter(path => !path.startsWith('/tags/'))
                    .filter(path => path !== window.location.pathname);
                if (urls.length) {
                    window.location = urls[Math.floor(Math.random() * urls.length)];
                }
            } catch (e) {
                alert('Could not fetch random page.');
            }
        });
    }
});
</script>
<!-- <a href="#" id="feeling-lucky-link" style="background-color: var(--bg); padding: 2px 6px; border-radius: 4px;">I'm feeling lucky</a> -->
'''

# # Collection to display on home
# homeCollectionTitle = 'Projects'
# homeCollection = 'projects'

# Collection to display on home
homeSections = ['projects', 'other']

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/Geoc2022"

[[params.social]]
name = "gmail"
url = "mailto:george_chemmala@brown.edu"

# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "other"
url = "/other"

[[params.about]]
name = "whoami"
url = "/whoami"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'arduino'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[markup.goldmark.renderer]
unsafe = true
